server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: patient
          uri: http://patient-service:8082
          predicates:
            - Path=/patients/**

        - id: notes
          uri: http://notes-service:8083
          predicates:
            - Path=/notes/**

        - id: risk
          uri: http://risk-assessment-service:8084
          predicates:
            - Path=/assess-risk/**